# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbd0bc6ae8e04221661fbe73b0113fbee3f9d74809e43d1a94ec85b0d2ae509062eabb41d08fee0a14b2f1a34562c355edd908754161c3df2d0d1ce6680e93b

test:
  secret_key_base: 3c27770064449c96b6068073cc83bb1d77e06785d9d7c1b60cb4e4c44a5b7c023839b19f01069df6a77f1b78a8c4928885db98dccd461fb9b095aa4ffc5a51fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
